# SwiftLint for swabble
included:
  - Sources
excluded:
  - .build
  - DerivedData
  - "**/.swiftpm"
  - "**/.build"
  - "**/DerivedData"
  - "**/.DS_Store"
opt_in_rules:
  - array_init
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

disabled_rules:
  - trailing_whitespace
  - trailing_newline
  - indentation_width
  - identifier_name
  - explicit_self
  - file_header
  - todo

line_length:
  warning: 140
  error: 180

reporter: "xcode"
